namespace ArenaGame.Heroes;

public class Mutant : Hero
{
    public int Armor { get; set; }
    public int MutationCoeficient { get; private set; } 
    public double MagicPower { get;private set; } 
    
    public double Bane { get; set; } 

    public Mutant(string name, double armor, double strength, IWeapon weapon, double health)
        : base(name, armor, strength, weapon, health)
    {
        Armor = 3;
        MutationCoeficient  = 0;
        MagicPower = 2;
        Bane = 2;
    }

    public override double Attack()
    {
        double DamageByWeapon= base.Attack();
        double spellDamage = UseMagic();
        return DamageByWeapon + spellDamage;
    }

    public override double Defend(double damage)
    {
        if ( MutationCoeficient > 0)
        {
            MutationCoeficient--;
            double lowDamage = UseBane();
            if (lowDamage > 0)
            {
                damage -= lowDamage;
                if (damage < 0) damage = 0;
            }
        }

        Fight();
        return base.Defend(damage);
    }

    public double UseMagic()
    {
        if (MagicPower > 0)
        {
            MagicPower--;
            return Strenght * 1.5;
        }

        return 0;
    }

    public double UseBane()
    {
        if (Bane > 0)
        {
            Bane--;
            return Strenght * 1.2;
        }

        return 0;
    }

    public void Mutate()
    {
        if ( MutationCoeficient < 2)
        {
            int mutationEffect = random.Next(1,4); 
            if (mutationEffect == 1)
            {
                Strenght += 1.2;
                MutationCoeficient++;
                Console.WriteLine("---The mutation gave increased strength---");
            }
            else if (mutationEffect == 2)
            {
                Armor += 2;
                MutationCoeficient++;
                Console.WriteLine("----Armor is regenerated by mutation---");
            }
            else if (mutationEffect == 3)
            {
                MagicPower += 2;
                Health /= 2;
                MutationCoeficient++;
                Console.WriteLine("----Magic abilities are increased by mutation---");
            }
            else
            {
                Console.WriteLine("----Mutant cannot use mutation effect---");
            }
        }
    }

    public void Fight()
    {
        int effect = random.Next(1, 4); 
        switch (effect)
        {
            case 1:
                Console.WriteLine("------Mutant casts a spell-------");
                UseMagic();
                break;
            case 2:
                Console.WriteLine("------Mutant injects bane---------");
                UseBane();
                break;
            case 3:
                Console.WriteLine("-_-_-_-_-_Mutation-_-_-_-_-_-");
                Mutate();
                break;
            default:
                Console.WriteLine("-_-_-_-_-_-Mutant cannot mutate-_-_-_-_-_");
                break;
        }
    }
}
